In [1]:
import torch

x = torch.Tensor([2,3])
y = torch.Tensor([3,2])
print(x*y)

tensor([6., 6.])


In [3]:
z = torch.zeros([3,5])
print(z)
print(z.shape)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([3, 5])


In [4]:
a = torch.rand([2,5])
print(a)

tensor([[0.7317, 0.8140, 0.8392, 0.0309, 0.6696],
        [0.3192, 0.4717, 0.2788, 0.2426, 0.4307]])


In [5]:
a = a.view([1,10])
print(a)

tensor([[0.7317, 0.8140, 0.8392, 0.0309, 0.6696, 0.3192, 0.4717, 0.2788, 0.2426,
         0.4307]])


In [6]:
a = a.view([2,5])
print(a)

tensor([[0.7317, 0.8140, 0.8392, 0.0309, 0.6696],
        [0.3192, 0.4717, 0.2788, 0.2426, 0.4307]])
